[project]
name = "company-clasterization"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Mikhail M.", email = "@datanalist"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "AGPL-3.0"}


[tool.pdm]
distribution = false
