[project]
name = "company-clasterization"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Mikhail M.", email = "@datanalist"},
]
dependencies = ["fastapi>=0.115.12", "uvicorn>=0.34.0", "bcrypt>=4.3.0", "pydantic>=2.11.2", "pre-commit>=4.2.0", "pyupgrade>=3.19.1", "check-jsonschema>=0.32.1", "detect-secrets>=1.5.0", "ipykernel>=6.29.5", "pandas>=2.2.3", "python-dotenv>=1.1.0", "nest-asyncio>=1.6.0", "bs4>=0.0.2", "aiohttp>=3.11.16", "ydata-profiling>=4.16.1", "telethon>=1.39.0", "setuptools>=78.1.0", "ipywidgets>=8.1.5", "transformers>=4.51.1", "razdel>=0.5.0", "numpy<2.0.0,>=1.21.0", "torch==2.5.0", "torchvision==0.20.0", "torchaudio==2.5.0", "sentence-transformers==3.3.1", "nltk>=3.9.1", "scikit-learn>=1.7.0", "umap-learn>=0.5.7", "hdbscan>=0.8.40", "streamlit>=1.46.0", "python-jose[cryptography]>=3.5.0", "passlib[bcrypt]>=1.7.4", "plotly>=6.1.2", "keybert>=0.9.0"]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "AGPL-3.0"}


[tool.pdm]
distribution = false
